services:
  db:
    image: "postgres:15.10"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: grana_go_development
      POSTGRES_PASSWORD: pgpass
    volumes:
      - ./.data:/var/lib/postgresql/data
  redis:
    image: "redis:7.2.7-alpine"
    command: redis-server
    ports:
     - 6379:6379
