
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: grana_go_development
  username: postgres
  password: pgpass
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: grana_go_test
  username: postgres
  password: pgpass
  host: 127.0.0.1
  port: 5432


production:
  primary: &primary_production
    <<: *default
    database: grana_go_production
    username: grana_go
    password: <%= ENV["GRANA_GO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: grana_go_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: grana_go_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: grana_go_production_cable
    migrations_paths: db/cable_migrate
